web:
    build: .
    command: python web.py
    container_name: queue_web
    volumes:
     - ./:/app/src
    ports:
     - "80:5000"
    links: 
     - redis
     - gearman
    environment:
     - APP_MODE=dev

daemon:
    build: .
    command: python daemon.py
    container_name: queue_daemon
    volumes:
     - ./:/app/src
    links:
     - redis
     - gearman
    environment:
     - APP_MODE=dev

redis:
    image: redis
    container_name: queue_redis
    expose:
     - "6379"

gearman:
    image: pataquets/gearmand
    container_name: queue_gearman
    expose:
     - "4730"